//  AUTH ACTIONS
export const APP_SIGN_IN = "APP_SIGN_IN";
export const APP_SIGN_OUT = "APP_SIGN_OUT";
export const APP_SIGN_IN_ERROR = "APP_SIGN_IN_ERROR";



// CURRENT USER ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";



// UI ACTIONS
export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const TOGGLE_OVERLAY_OFF = "TOGGLE_OVERLAY_OFF";
export const TOGGLE_LOGIN_OVERLAY = "TOGGLE_LOGIN_OVERLAY";
export const TOGGLE_SIGNUP_OVERLAY = "TOGGLE_SIGNUP_OVERLAY";
export const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";
