//  AUTH ACTIONS
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

// CURRENT USER ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// UI ACTIONS
export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const TOGGLE_OVERLAY_OFF = "TOGGLE_OVERLAY_OFF";
export const TOGGLE_LOGIN_OVERLAY = "TOGGLE_LOGIN_OVERLAY";
export const TOGGLE_SIGNUP_OVERLAY = "TOGGLE_SIGNUP_OVERLAY";
export const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";

// RECIPE ACTIONS
export const CREATE_RECIPE = "CREATE_RECIPE";
export const SET_SELECTED_RECIPE = "SET_SELECTED_RECIPE";
